-- ============================================================
-- Ceres Trade Promotions — Schema & Table Setup
-- Run this script first to create the database objects.
-- ============================================================

-- 1. Database & Schema
CREATE DATABASE IF NOT EXISTS CERES_TRADE_PROMO;
USE DATABASE CERES_TRADE_PROMO;

CREATE SCHEMA IF NOT EXISTS TRADE_ANALYTICS;
USE SCHEMA TRADE_ANALYTICS;

-- 2. Warehouse (use an existing XS warehouse or create one)
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

USE WAREHOUSE COMPUTE_WH;

-- ============================================================
-- DIMENSION TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS DIM_RETAILER (
  RETAILER_ID   NUMBER(38,0)   NOT NULL,
  RETAILER_NAME VARCHAR(100),
  COUNTRY       VARCHAR(50),
  CHANNEL       VARCHAR(50),
  COVERAGE_TYPE VARCHAR(20),
  STORE_COUNT   NUMBER(38,0),
  PRIMARY KEY (RETAILER_ID)
);

CREATE TABLE IF NOT EXISTS DIM_PPG (
  PPG_ID             NUMBER(38,0)   NOT NULL,
  PPG_NAME           VARCHAR(200),
  PACK_SIZE          VARCHAR(50),
  SUGAR_VARIANT      VARCHAR(30),
  REGULAR_PRICE_IDR  NUMBER(12,0),
  CATEGORY           VARCHAR(50),
  IS_LIMITED_EDITION BOOLEAN,
  PRIMARY KEY (PPG_ID)
);

CREATE TABLE IF NOT EXISTS DIM_CALENDAR (
  WEEK_ID     NUMBER(38,0) NOT NULL,
  WEEK_START  DATE,
  WEEK_END    DATE,
  YEAR        NUMBER(38,0),
  QUARTER     NUMBER(38,0),
  MONTH       NUMBER(38,0),
  PERIOD_NAME VARCHAR(20),
  PRIMARY KEY (WEEK_ID)
);

-- ============================================================
-- FACT TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS FACT_TRADE_CALENDAR (
  PROMO_ID            NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
  RETAILER_ID         NUMBER(38,0),
  PPG_ID              NUMBER(38,0),
  WEEK_START          DATE,
  WEEK_END            DATE,
  DISCOUNT_IDR        NUMBER(12,0),
  DISCOUNT_PCT        NUMBER(5,2),
  PROMO_TYPE          VARCHAR(20),
  PLANNED_SPEND_IDR   NUMBER(14,0),
  PLANNED_VOLUME_CASES NUMBER(38,0),
  COVERAGE            VARCHAR(20),
  PLANNED_HAS_DISPLAY BOOLEAN,
  PLANNED_HAS_FEATURE BOOLEAN,
  STATUS              VARCHAR(20) DEFAULT 'COMPLETED',
  PRIMARY KEY (PROMO_ID)
);

CREATE TABLE IF NOT EXISTS FACT_POS_ACTUALS (
  POS_ID              NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
  RETAILER_ID         NUMBER(38,0),
  PPG_ID              NUMBER(38,0),
  WEEK_ID             NUMBER(38,0),
  ACTUAL_PRICE_IDR    NUMBER(12,0),
  ACTUAL_VOLUME_CASES NUMBER(38,0),
  BASE_VOLUME_CASES   NUMBER(38,0),
  IS_ON_FEATURE       BOOLEAN,
  IS_ON_DISPLAY       BOOLEAN,
  IS_PROMOTED         BOOLEAN,
  PRIMARY KEY (POS_ID)
);

CREATE TABLE IF NOT EXISTS FACT_COMPLIANCE_SCORES (
  COMPLIANCE_ID          NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
  PROMO_ID               NUMBER(38,0),
  PRICE_ACCURACY_PCT     NUMBER(5,2),
  DISPLAY_COMPLIANCE_PCT NUMBER(5,2),
  FEATURE_COMPLIANCE_PCT NUMBER(5,2),
  OVERALL_COMPLIANCE_PCT NUMBER(5,2),
  COMPLIANCE_STATUS      VARCHAR(20),
  PRIMARY KEY (COMPLIANCE_ID)
);

CREATE TABLE IF NOT EXISTS FACT_LIFT_ANALYSIS (
  LIFT_ID                     NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
  PROMO_ID                    NUMBER(38,0),
  BASE_VOLUME_CASES           NUMBER(38,0),
  INCREMENTAL_VOLUME_CASES    NUMBER(38,0),
  TOTAL_PROMOTED_VOLUME_CASES NUMBER(38,0),
  LIFT_PCT                    NUMBER(8,2),
  SPEND_IDR                   NUMBER(14,0),
  INCREMENTAL_REVENUE_IDR     NUMBER(14,0),
  ROI                         NUMBER(8,2),
  PRIMARY KEY (LIFT_ID)
);

CREATE TABLE IF NOT EXISTS FACT_OPTIMIZATION_SCENARIOS (
  SCENARIO_ID   NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
  USER_ID       VARCHAR(100),
  SCENARIO_NAME VARCHAR(200),
  CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PARAMETERS    VARIANT,
  RESULTS       VARIANT,
  IS_ACTIVE     BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (SCENARIO_ID)
);

-- Done. Run 02-seed-dimensions.sql next.
